export const STATEMENT_SKILL_CTO = 0;
export const STATEMENT_SKILL_SOLIDITY = 1;
export const STATEMENT_SKILL_TYPESCRIPT = 2;

export const STATEMENT_SKILLS = [
  STATEMENT_SKILL_CTO,
  STATEMENT_SKILL_SOLIDITY,
  STATEMENT_SKILL_TYPESCRIPT,
];

export const STATEMENT_EVALUATIONS = [5, 4, 3, 2, 1];
